import { supabase } from "@/lib/supabase";
import type { User } from "@supabase/supabase-js";

/**
 * Lists data layer — typed query options + mutation functions. Components
 * call these via createQuery / createMutation from @tanstack/solid-query.
 *
 * Naming convention:
 *   - listsQueryKey()             — overview (all visible lists)
 *   - listQueryKey(id)            — single list detail
 *   - listItemsQueryKey(id)       — items inside one list
 *
 * Mutations invalidate the keys they touch. Realtime subscriptions (added in
 * the chunk after this) call queryClient.invalidateQueries on the same keys
 * so a partner's write flows to your screen the same way your own does —
 * one source of truth for "this data changed", whether the trigger was local
 * or remote.
 *
 * RLS does the visibility filtering on every query — we never pass user_id
 * filters explicitly; lists_select_member + list_items_select_member +
 * list_members_select_co already scope the rows correctly.
 */

// ──────────────────────────────────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────────────────────────────────

export interface ListSummary {
  /** UUID — used for RPC calls (delete, rename, set-tracks-home). */
  id: string;
  /** URL-stable identifier — `adj-adj-noun`, generated by the DB trigger
   *  `lists_set_short_code_trigger` on insert. Used in `/lists/<shortCode>`
   *  and in TanStack-Query keys. */
  shortCode: string;
  name: string;
  description: string | null;
  isShared: boolean;
  /** Caller's per-user tracks_home flag. Off → archive (lists I created but
   *  don't want to surface on Home / Calendar). */
  tracksHome: boolean;
  ownerId: string;
  createdAt: string;
  itemCount: number;
  memberCount: number;
  /** True when the caller is the list's creator. Used to gate the "Liste
   *  löschen" action (everyone else gets "Liste verlassen" once sharing
   *  lands). */
  isOwner: boolean;
  /** Caller's per-user pin state. Pinned lists float to the top of the
   *  caller's /lists view (independent of what other members see). */
  pinned: boolean;
  /** Caller's per-user manual sort_order. Higher pin / lower sort_order =
   *  closer to the top within its pin section. */
  sortOrder: number;
}

export interface ListEntry {
  listItemId: string;
  itemId: string;
  /** (type, slug) is the natural key used in `/item/:type/:slug`. */
  type: string;
  slug: string;
  title: string;
  coverUrl: string | null;
  syncEnabled: boolean;
  /** Shared per-list pin state. Pinning an item is visible to every member
   *  of the list, unlike the per-user list pin above. */
  pinned: boolean;
  sortOrder: number;
}

// ──────────────────────────────────────────────────────────────────────────
// Query keys — exported so realtime + mutations can invalidate by key
// ──────────────────────────────────────────────────────────────────────────

export const listsQueryKey = ["lists"] as const;
// Per-list keys are now indexed by shortCode (URL-stable). Realtime
// invalidations use this key + a channel name derived from the shortCode.
export const listQueryKey = (shortCode: string) =>
  ["list", shortCode] as const;
export const listItemsQueryKey = (shortCode: string) =>
  ["list", shortCode, "items"] as const;

// ──────────────────────────────────────────────────────────────────────────
// Query options — pass to createQuery() in components
// ──────────────────────────────────────────────────────────────────────────

/** PostgREST embed shape — list_items(count) and list_members(count) return
 *  as a single-element array of { count }. */
interface RawListRow {
  id: string;
  short_code: string;
  name: string;
  description: string | null;
  is_shared: boolean;
  owner_id: string;
  created_at: string;
  list_items: { count: number }[] | null;
  list_members: { count: number }[] | null;
}

const LIST_SELECT =
  "id, short_code, name, description, is_shared, owner_id, created_at, list_items(count), list_members(count)";

function toSummary(
  row: RawListRow,
  user: User,
  membership: { tracksHome: boolean; pinned: boolean; sortOrder: number },
): ListSummary {
  return {
    id: row.id,
    shortCode: row.short_code,
    name: row.name,
    description: row.description,
    isShared: row.is_shared,
    tracksHome: membership.tracksHome,
    ownerId: row.owner_id,
    createdAt: row.created_at,
    itemCount: row.list_items?.[0]?.count ?? 0,
    memberCount: row.list_members?.[0]?.count ?? 0,
    isOwner: row.owner_id === user.id,
    pinned: membership.pinned,
    sortOrder: membership.sortOrder,
  };
}

/** Pinned-first, then by sort_order ASC within each section. Server can't
 *  express "group by (pinned_at IS NULL) then sort by sort_order" without a
 *  generated column or RPC, so we group client-side. With < 100 lists this
 *  is free. */
function bySectionThenSort(a: ListSummary, b: ListSummary): number {
  if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
  return a.sortOrder - b.sortOrder;
}

/**
 * All lists visible to the current user (RLS scopes via lists_select_member).
 * Split into private / shared so the UI can render the two groups; the split
 * is by is_shared, not ownership — a list you created becomes "geteilt" the
 * moment you invite someone (Phase 7+).
 *
 * Two parallel queries: lists+embedded counts, and the caller's own
 * list_members rows for tracks_home. The original Logbook also fetched
 * "newCounts" for episode badges — deferred until items + episodes land
 * in Phases 4–5.
 */
interface RawMembershipJoinRow {
  pinned_at: string | null;
  sort_order: number;
  tracks_home: boolean;
  lists: RawListRow;
}

export function listsQueryOptions(user: User) {
  return {
    queryKey: listsQueryKey,
    queryFn: async (): Promise<{
      private: ListSummary[];
      shared: ListSummary[];
    }> => {
      // Drive from list_members so the per-user pin / sort_order live on
      // the same row as the membership flag. lists!inner embeds the parent
      // list (single object, not array — many-to-one FK). RLS scopes both
      // sides: list_members WHERE user_id=me + lists_select_member on the
      // embed.
      const { data, error } = await supabase
        .from("list_members")
        .select(
          `pinned_at, sort_order, tracks_home, lists!inner(${LIST_SELECT})`,
        )
        .eq("user_id", user.id);

      if (error) throw error;

      const rows = (data ?? []) as unknown as RawMembershipJoinRow[];
      const summaries = rows
        .map((r) =>
          toSummary(r.lists, user, {
            tracksHome: r.tracks_home,
            pinned: r.pinned_at !== null,
            sortOrder: r.sort_order,
          }),
        )
        .sort(bySectionThenSort);

      return {
        private: summaries.filter((l) => !l.isShared),
        shared: summaries.filter((l) => l.isShared),
      };
    },
  };
}

/** A single list by short_code, or null if not visible (RLS) / unknown
 *  code. Membership lookup happens after we've got the list-id, because
 *  list_members is keyed on the UUID. */
export function listQueryOptions(user: User, shortCode: string) {
  return {
    queryKey: listQueryKey(shortCode),
    queryFn: async (): Promise<ListSummary | null> => {
      const listRes = await supabase
        .from("lists")
        .select(LIST_SELECT)
        .eq("short_code", shortCode)
        .maybeSingle();

      if (listRes.error) throw listRes.error;
      if (!listRes.data) return null;

      const raw = listRes.data as unknown as RawListRow;
      const membershipRes = await supabase
        .from("list_members")
        .select("tracks_home, pinned_at, sort_order")
        .eq("list_id", raw.id)
        .eq("user_id", user.id)
        .maybeSingle();

      const m = membershipRes.data as
        | { tracks_home: boolean; pinned_at: string | null; sort_order: number }
        | null;
      return toSummary(raw, user, {
        tracksHome: m?.tracks_home ?? true,
        pinned: m?.pinned_at != null,
        sortOrder: m?.sort_order ?? 0,
      });
    },
  };
}

interface RawListItemRow {
  id: string;
  sync_enabled: boolean;
  item_id: string;
  pinned_at: string | null;
  sort_order: number;
  items: {
    title: string;
    type: string;
    slug: string;
    cover_url: string | null;
  } | null;
}

/** Items placed in a list, ordered pinned-first then by sort_order ASC,
 *  scoped by the list's short_code. PostgREST `lists!inner(short_code)`
 *  does the FK join + filter in one round-trip; RLS still scopes the rows
 *  to lists the caller can see. Pin grouping happens client-side (see
 *  `bySectionThenSort` rationale on the lists query above). */
export function listItemsQueryOptions(shortCode: string) {
  return {
    queryKey: listItemsQueryKey(shortCode),
    queryFn: async (): Promise<ListEntry[]> => {
      const { data, error } = await supabase
        .from("list_items")
        .select(
          "id, sync_enabled, item_id, pinned_at, sort_order, lists!inner(short_code), items(title, type, slug, cover_url)",
        )
        .eq("lists.short_code", shortCode);
      if (error) throw error;
      const rows = ((data as unknown as RawListItemRow[]) ?? []).map((r) => ({
        listItemId: r.id,
        itemId: r.item_id,
        type: r.items?.type ?? "anime",
        slug: r.items?.slug ?? "",
        title: r.items?.title ?? "Unbekannt",
        coverUrl: r.items?.cover_url ?? null,
        syncEnabled: r.sync_enabled,
        pinned: r.pinned_at !== null,
        sortOrder: r.sort_order,
      }));
      return rows.sort((a, b) => {
        if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
        return a.sortOrder - b.sortOrder;
      });
    },
  };
}

// ──────────────────────────────────────────────────────────────────────────
// Mutations — components compose these via createMutation
// ──────────────────────────────────────────────────────────────────────────

export async function createList(
  user: User,
  input: { name: string; description?: string },
): Promise<ListSummary> {
  const name = input.name.trim();
  if (!name) throw new Error("Name darf nicht leer sein.");

  const { data, error } = await supabase
    .from("lists")
    .insert({
      owner_id: user.id,
      name,
      description: input.description?.trim() || null,
    })
    .select(LIST_SELECT)
    .single();

  if (error) throw error;
  // The on_list_created trigger added the owner to list_members with
  // tracks_home=true automatically. The new list_members row gets
  // pinned_at=null and a sort_order assigned by the BEFORE-INSERT trigger
  // (MIN(scope)-1 → top of unpinned section). We don't read those back
  // here — the next invalidation refresh picks them up. For the optimistic
  // returnee we use safe defaults.
  return toSummary(data as unknown as RawListRow, user, {
    tracksHome: true,
    pinned: false,
    sortOrder: 0,
  });
}

/**
 * Rename. RLS (lists_update_member) lets any member rename. We `.select()`
 * the persisted name back so an RLS-blocked write (0 rows, no error)
 * surfaces as a returned `name: null` — components compare to detect the
 * silent block.
 */
export async function renameList(input: {
  listId: string;
  name: string;
}): Promise<{ name: string | null }> {
  const next = input.name.trim();
  if (!next) return { name: null };

  const { data, error } = await supabase
    .from("lists")
    .update({ name: next })
    .eq("id", input.listId)
    .select("name")
    .maybeSingle();
  if (error) throw error;
  return { name: (data as { name: string } | null)?.name ?? null };
}

/** Delete a list. RLS (lists_delete_owner) restricts to the creator; the
 *  cascade on list_items / list_members / list_invitations cleans the rest. */
export async function deleteList(listId: string): Promise<void> {
  const { error } = await supabase.from("lists").delete().eq("id", listId);
  if (error) throw error;
}

/** Remove an item from a list (delete the list_items row). The item itself
 *  stays in `items` — it's still in the catalogue, just no longer on this
 *  list. Watch progress is keyed on items.id, so it's preserved even if the
 *  same item gets re-added later. */
export async function removeListItem(listItemId: string): Promise<void> {
  const { error } = await supabase
    .from("list_items")
    .delete()
    .eq("id", listItemId);
  if (error) throw error;
}

/** Move a list_items row to a different list. Sync is reset to false because
 *  the new list may have different members — if the caller wants sync in the
 *  new list, they re-enable it there (handshake §Phase 7). */
export async function moveListItem(input: {
  listItemId: string;
  targetListId: string;
}): Promise<void> {
  const { error } = await supabase
    .from("list_items")
    .update({ list_id: input.targetListId, sync_enabled: false })
    .eq("id", input.listItemId);
  if (error) throw error;
}

/**
 * Toggle the per-user tracks_home flag. Off = archive mode for the caller
 * only — items in this list drop off Home / Calendar / Logbook for them.
 * Other members keep their own setting.
 *
 * `.select()` to detect silent RLS blocks (0 rows updated, no error).
 */
export async function setListTracking(
  user: User,
  input: { listId: string; enabled: boolean },
): Promise<{ tracksHome: boolean | null }> {
  const { data, error } = await supabase
    .from("list_members")
    .update({ tracks_home: input.enabled })
    .eq("list_id", input.listId)
    .eq("user_id", user.id)
    .select("tracks_home")
    .maybeSingle();
  if (error) throw error;
  return {
    tracksHome:
      (data as { tracks_home: boolean } | null)?.tracks_home ?? null,
  };
}

/**
 * Toggle the per-user list pin on `list_members`. Also assigns a fresh
 * sort_order so the pinned (or freshly-unpinned) list lands at the TOP of
 * its new section — `MIN(section.sort_order) - 1`. The caller computes
 * `sortOrder` from the current query cache so we don't need an extra
 * round-trip. Returns the post-write pinned state so the caller can
 * detect silent RLS blocks (0 rows → null).
 */
export async function setListPin(input: {
  listId: string;
  userId: string;
  pinned: boolean;
  sortOrder: number;
}): Promise<{ pinned: boolean | null }> {
  const { data, error } = await supabase
    .from("list_members")
    .update({
      pinned_at: input.pinned ? new Date().toISOString() : null,
      sort_order: input.sortOrder,
    })
    .eq("list_id", input.listId)
    .eq("user_id", input.userId)
    .select("pinned_at")
    .maybeSingle();
  if (error) throw error;
  return {
    pinned: data ? (data as { pinned_at: string | null }).pinned_at !== null : null,
  };
}

/**
 * Toggle the shared per-list pin on `list_items`. Same sortOrder-bump
 * pattern as setListPin so the pinned/unpinned item floats to the top of
 * its new section.
 */
export async function setListItemPin(input: {
  listItemId: string;
  pinned: boolean;
  sortOrder: number;
}): Promise<{ pinned: boolean | null }> {
  const { data, error } = await supabase
    .from("list_items")
    .update({
      pinned_at: input.pinned ? new Date().toISOString() : null,
      sort_order: input.sortOrder,
    })
    .eq("id", input.listItemId)
    .select("pinned_at")
    .maybeSingle();
  if (error) throw error;
  return {
    pinned: data ? (data as { pinned_at: string | null }).pinned_at !== null : null,
  };
}

/**
 * Rewrite sort_order for a slice of the caller's list_members rows. The
 * slice is one pin section (pinned OR unpinned) of `/lists` — drag-reorder
 * never crosses the pin boundary (handshake §session-3 scope decision), so
 * only the moved section needs its sort_order rewritten in one go.
 *
 * Fires N parallel UPDATEs (one per row). Atomicity is best-effort — a
 * partial failure leaves a coherent but possibly stale order; the next
 * refetch reconciles. For >50-list users we'd move to a single-statement
 * RPC `reorder_list_members(_user_id, _ordered_list_ids)`.
 */
export async function reorderLists(input: {
  userId: string;
  orderedListIds: string[];
}): Promise<void> {
  await Promise.all(
    input.orderedListIds.map((listId, idx) =>
      supabase
        .from("list_members")
        .update({ sort_order: idx + 1 })
        .eq("list_id", listId)
        .eq("user_id", input.userId),
    ),
  );
}

/** Same idea as reorderLists but for the shared per-list item ordering on
 *  list_items. Sync is server-side per-row UPDATE; partial-failure caveat
 *  identical. */
export async function reorderListItems(input: {
  orderedListItemIds: string[];
}): Promise<void> {
  await Promise.all(
    input.orderedListItemIds.map((id, idx) =>
      supabase
        .from("list_items")
        .update({ sort_order: idx + 1 })
        .eq("id", id),
    ),
  );
}
