import { supabase } from "@/lib/supabase";
import type { User } from "@supabase/supabase-js";
import { embedCount, snapToWeekday, unique } from "@/lib/format";

/**
 * Lists data layer — typed query options + mutation functions. Components
 * call these via createQuery / createMutation from @tanstack/solid-query.
 *
 * Naming convention:
 *   - listsQueryKey()             — overview (all visible lists)
 *   - listQueryKey(id)            — single list detail
 *   - listItemsQueryKey(id)       — items inside one list
 *
 * Mutations invalidate the keys they touch. Realtime subscriptions (added in
 * the chunk after this) call queryClient.invalidateQueries on the same keys
 * so a partner's write flows to your screen the same way your own does —
 * one source of truth for "this data changed", whether the trigger was local
 * or remote.
 *
 * RLS does the visibility filtering on every query — we never pass user_id
 * filters explicitly; lists_select_member + list_items_select_member +
 * list_members_select_co already scope the rows correctly.
 */

// ──────────────────────────────────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────────────────────────────────

/** The five real list categories (1:1 with item types, minus `music`). A list
 *  can carry one of these OR none — null is "Alle" (uncategorized), the default
 *  state where the list lives in "Meine Listen" and the AddSheet imposes no
 *  type restriction. A non-null category is the primary grouping axis on /lists
 *  and locks the AddSheet's type filter to it. */
export type ListCategory = "anime" | "manga" | "series" | "movie" | "game";

/** Fixed display order + labels for the category sections on /lists and the
 *  category picker. Section names read as the plural-ish category, not the
 *  singular `typeLabel` (Serie → Serien, Film → Filme, Spiel → Spiele). */
export const LIST_CATEGORIES: { value: ListCategory; label: string }[] = [
  { value: "anime", label: "Anime" },
  { value: "manga", label: "Manga" },
  { value: "series", label: "Serien" },
  { value: "movie", label: "Filme" },
  { value: "game", label: "Spiele" },
];

/** Display label for a category — shared by the detail switcher, the AddSheet
 *  lock ("Nur <Kategorie>") and the move dialog's mismatch toast. */
export function listCategoryLabel(cat: ListCategory): string {
  return LIST_CATEGORIES.find((c) => c.value === cat)?.label ?? cat;
}

export interface ListSummary {
  /** UUID — used for RPC calls (delete, rename, set-tracks-home). */
  id: string;
  /** URL-stable identifier — `adj-adj-noun`, generated by the DB trigger
   *  `lists_set_short_code_trigger` on insert. Used in `/lists/<shortCode>`
   *  and in TanStack-Query keys. */
  shortCode: string;
  name: string;
  description: string | null;
  /** The list's media category, or null for "Alle" (uncategorized). Set by the
   *  owner only; members read it. Drives sectioning + AddSheet type-lock. */
  category: ListCategory | null;
  isShared: boolean;
  /** Caller's per-user tracks_home flag. Off → archive (lists I created but
   *  don't want to surface on Home / Calendar). */
  tracksHome: boolean;
  ownerId: string;
  createdAt: string;
  /** Owner-uploaded custom cover (public storage URL). Null → render the
   *  generated GeneratedCover from coverSeed instead. */
  coverUrl: string | null;
  /** Deterministic seed for the generated default cover (random theme +
   *  pattern). Assigned by the DB default on insert. */
  coverSeed: number;
  itemCount: number;
  memberCount: number;
  /** True when the caller is the list's creator. Used to gate the "Liste
   *  löschen" action (everyone else gets "Liste verlassen" once sharing
   *  lands). */
  isOwner: boolean;
  /** Caller's per-user pin state. Pinned lists float to the top of the
   *  caller's /lists view (independent of what other members see). */
  pinned: boolean;
  /** Caller's per-user manual sort_order. Higher pin / lower sort_order =
   *  closer to the top within its pin section. */
  sortOrder: number;
  /** Total released-but-unwatched EPISODES/chapters across the list in the
   *  last NEW_WINDOW_DAYS — drives the "Neue Folge"/"Neue Folgen" badge on
   *  /lists rows (count is summed per episode, not per item, so a same-day
   *  batch release reads as plural). Only shown for tracked lists. Manga have
   *  no air-date signal, so the kapitel side stays 0 until that source lands
   *  (Welle-2). */
  newCounts: { folgen: number; kapitel: number };
}

export interface ListEntry {
  listItemId: string;
  itemId: string;
  /** (type, slug) is the natural key used in `/item/:type/:slug`. */
  type: string;
  slug: string;
  title: string;
  coverUrl: string | null;
  syncEnabled: boolean;
  /** Shared per-list pin state. Pinning an item is visible to every member
   *  of the list, unlike the per-user list pin above. */
  pinned: boolean;
  sortOrder: number;
  /** True when at least one episode of this item aired within the last
   *  NEW_WINDOW_DAYS and the caller hasn't ticked it yet. Drives the
   *  "Neue Folge" badge in the list-detail row. Per-user — co-members
   *  evaluate the same item independently against their own watches. */
  hasNewEpisode: boolean;
  /** How many such episodes — drives singular vs plural wording on the badge
   *  ("Neue Folge" vs "Neue Folgen"). 0 when hasNewEpisode is false. */
  newEpisodeCount: number;
}

// ──────────────────────────────────────────────────────────────────────────
// Query keys — exported so realtime + mutations can invalidate by key
// ──────────────────────────────────────────────────────────────────────────

export const listsQueryKey = ["lists"] as const;
// Per-list keys are now indexed by shortCode (URL-stable). Realtime
// invalidations use this key + a channel name derived from the shortCode.
export const listQueryKey = (shortCode: string) =>
  ["list", shortCode] as const;
export const listItemsQueryKey = (shortCode: string) =>
  ["list", shortCode, "items"] as const;

// ──────────────────────────────────────────────────────────────────────────
// Query options — pass to createQuery() in components
// ──────────────────────────────────────────────────────────────────────────

/** PostgREST embed shape — list_items(count) and list_members(count) return
 *  as a single-element array of { count }. */
interface RawListRow {
  id: string;
  short_code: string;
  name: string;
  description: string | null;
  category: string | null;
  is_shared: boolean;
  owner_id: string;
  created_at: string;
  cover_url: string | null;
  cover_seed: number;
  list_items: { count: number }[] | null;
  list_members: { count: number }[] | null;
}

const LIST_SELECT =
  "id, short_code, name, description, category, is_shared, owner_id, created_at, cover_url, cover_seed, list_items(count), list_members(count)";

function toSummary(
  row: RawListRow,
  user: User,
  membership: { tracksHome: boolean; pinned: boolean; sortOrder: number },
): Omit<ListSummary, "newCounts"> {
  return {
    id: row.id,
    shortCode: row.short_code,
    name: row.name,
    description: row.description,
    category: (row.category as ListCategory | null) ?? null,
    isShared: row.is_shared,
    tracksHome: membership.tracksHome,
    ownerId: row.owner_id,
    createdAt: row.created_at,
    coverUrl: row.cover_url,
    coverSeed: row.cover_seed,
    itemCount: embedCount(row.list_items),
    memberCount: embedCount(row.list_members),
    isOwner: row.owner_id === user.id,
    pinned: membership.pinned,
    sortOrder: membership.sortOrder,
  };
}

/** Empty new-counts default — used in places where we don't have the
 *  newItemsMap (single-list query, optimistic createList return). */
const EMPTY_COUNTS = { folgen: 0, kapitel: 0 } as const;

/** Pinned-first, then by sort_order ASC within each section. Server can't
 *  express "group by (pinned_at IS NULL) then sort by sort_order" without a
 *  generated column or RPC, so we group client-side. With < 100 lists this
 *  is free. */
function bySectionThenSort(a: ListSummary, b: ListSummary): number {
  if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
  return a.sortOrder - b.sortOrder;
}

/** Window matching the Logbuch's "missed" definition — a released episode
 *  counts as "new" if it aired in the last NEW_WINDOW_DAYS and the user
 *  hasn't ticked it. Keeps the lists badge and the home modules in sync. */
const NEW_WINDOW_DAYS = 14;

/** One list_item candidate for the new-episode check — carries its item plus
 *  the lane selector (sync-instances model). */
interface NewEpisodeEntry {
  itemId: string;
  listItemId: string;
  /** Synced → read this list_item's INSTANCE rows; else the caller's GLOBAL
   *  rows. */
  syncEnabled: boolean;
  /** Group-shared Anzeige-Tag of this synced instance (list_items.display_weekday).
   *  Ignored for non-synced entries (those take the per-user global override). */
  instanceWeekday: number | null;
}

/** Shared empty set for synced entries that have no instance rows yet — never
 *  mutated, so it's safe to alias. */
const EMPTY_EPISODE_SET: ReadonlySet<string> = new Set();

/**
 * Maps each LIST_ITEM that has released-but-unwatched episodes inside the
 * new-window to HOW MANY such episodes it has, reading EACH entry against its
 * correct progress lane (sync-instances model):
 *   - non-synced entry → the caller's GLOBAL watches (`list_item_id IS NULL`)
 *   - synced entry      → that list_item's INSTANCE watches (`list_item_id = LI`)
 * Keyed on listItemId (not itemId) because the same item can appear as both a
 * global and a synced entry across different lists, with different badges.
 * Entries with zero new episodes are absent from the map (so `map.has(id)` /
 * `(map.get(id) ?? 0) > 0` is the "has new" test). The count drives singular-
 * vs-plural wording ("Neue Folge" vs "Neue Folgen") — a single same-day batch
 * release is several new episodes on ONE item, which an item-count would miss.
 *
 * Round-trips: episodes-in-window, the caller's global watches over them, and
 * — only when some entry is synced — the instance watches in one bulk query.
 * The candidate set is passed in scoped (one list, or all visible lists), so we
 * never scan the user's full catalogue.
 */
async function findItemsWithNewEpisodes(
  userId: string,
  entries: NewEpisodeEntry[],
): Promise<Map<string, number>> {
  if (entries.length === 0) return new Map();

  const itemIds = unique(entries.map((e) => e.itemId));
  const now = Date.now();
  const sinceIso = new Date(now - NEW_WINDOW_DAYS * 86_400_000).toISOString();
  const nowIso = new Date(now).toISOString();
  const { data: epRows, error: epErr } = await supabase
    .from("episodes")
    .select("id, item_id, air_date")
    .in("item_id", itemIds)
    .gte("air_date", sinceIso)
    .lte("air_date", nowIso);
  if (epErr) {
    console.error("episodes window query failed", epErr);
    return new Map();
  }
  const eps = (epRows ?? []) as {
    id: string;
    item_id: string;
    air_date: string | null;
  }[];
  if (eps.length === 0) return new Map();
  const epIds = eps.map((e) => e.id);

  // Recent episodes (id + air_date) grouped by item, so each entry tests its
  // own item against its own lane's Anzeige-Tag.
  const epsByItem = new Map<string, { id: string; airDate: string | null }[]>();
  for (const e of eps) {
    const arr = epsByItem.get(e.item_id);
    const ep = { id: e.id, airDate: e.air_date };
    if (arr) arr.push(ep);
    else epsByItem.set(e.item_id, [ep]);
  }

  // Per-user global Anzeige-Tag overrides (non-synced entries snap by these;
  // synced entries use their instance's group-shared weekday). One small read.
  const { data: prefRows } = await supabase
    .from("item_display_prefs")
    .select("item_id, weekday")
    .eq("user_id", userId);
  const globalWeekday = new Map<string, number>();
  for (const p of prefRows ?? [])
    globalWeekday.set(p.item_id as string, p.weekday as number);

  // Global watched set (list_item_id IS NULL) — covers every non-synced entry.
  const { data: gRows, error: gErr } = await supabase
    .from("episode_watches")
    .select("episode_id")
    .eq("user_id", userId)
    .is("list_item_id", null)
    .in("episode_id", epIds);
  if (gErr) {
    console.error("episode_watches global join failed", gErr);
    return new Map();
  }
  const globalWatched = new Set((gRows ?? []).map((w) => w.episode_id as string));

  // Instance watched sets, grouped by list_item_id — one bulk query over all
  // synced list_items, fetched only when at least one entry is synced.
  const syncedIds = unique(
    entries.filter((e) => e.syncEnabled).map((e) => e.listItemId),
  );
  const instanceWatched = new Map<string, Set<string>>();
  if (syncedIds.length > 0) {
    const { data: iRows, error: iErr } = await supabase
      .from("episode_watches")
      .select("episode_id, list_item_id")
      .eq("user_id", userId)
      .in("list_item_id", syncedIds)
      .in("episode_id", epIds);
    if (iErr) {
      console.error("episode_watches instance join failed", iErr);
    } else {
      for (const r of iRows ?? []) {
        const li = r.list_item_id as string;
        let set = instanceWatched.get(li);
        if (!set) instanceWatched.set(li, (set = new Set()));
        set.add(r.episode_id as string);
      }
    }
  }

  const result = new Map<string, number>();
  for (const entry of entries) {
    const itemEps = epsByItem.get(entry.itemId);
    if (!itemEps) continue;
    const watched = entry.syncEnabled
      ? instanceWatched.get(entry.listItemId) ?? EMPTY_EPISODE_SET
      : globalWatched;
    // Anzeige-Tag for this lane: synced → the instance's group value, else the
    // viewer's global override. An episode only counts as "new" once its SNAPPED
    // availability day has arrived — a Mon-aired episode with a Fri override
    // surfaces as a badge on Friday, not before. (Snap moves ≥0 days forward, so
    // the fetched [now-14d, now] window already covers every snapped result.)
    const weekday = entry.syncEnabled
      ? entry.instanceWeekday
      : globalWeekday.get(entry.itemId) ?? null;
    const unwatched = itemEps.reduce((n, ep) => {
      if (watched.has(ep.id)) return n;
      if (!ep.airDate) return n + 1;
      return new Date(snapToWeekday(ep.airDate, weekday)).getTime() <= now
        ? n + 1
        : n;
    }, 0);
    if (unwatched > 0) result.set(entry.listItemId, unwatched);
  }
  return result;
}

/** Aggregate (list_id, listItemId, type) entries into per-list (folgen,
 *  kapitel) counts — summing the NEW-EPISODE COUNT per qualifying list_item,
 *  not just the item tally, so the singular/plural wording reflects "more than
 *  one new episode" even when they sit on a single item (a same-day batch
 *  release). anime/series count as Folgen, manga as Kapitel; movies/games are
 *  ignored (no episode model). Type + listItemId travel alongside so we don't
 *  need a separate items lookup, and the lookup keys on listItemId (sync-aware). */
function aggregateNewCounts(
  pairs: { list_id: string; listItemId: string; type: string }[],
  newEpisodeCounts: Map<string, number>,
): Map<string, { folgen: number; kapitel: number }> {
  const counts = new Map<string, { folgen: number; kapitel: number }>();
  for (const p of pairs) {
    const n = newEpisodeCounts.get(p.listItemId) ?? 0;
    if (n === 0) continue;
    const c = counts.get(p.list_id) ?? { folgen: 0, kapitel: 0 };
    if (p.type === "manga") c.kapitel += n;
    else if (p.type === "anime" || p.type === "series") c.folgen += n;
    counts.set(p.list_id, c);
  }
  return counts;
}

/**
 * All lists visible to the current user (RLS scopes via lists_select_member).
 * Split into private / shared so the UI can render the two groups; the split
 * is by is_shared, not ownership — a list you created becomes "geteilt" the
 * moment you invite someone (Phase 7+).
 *
 * Two parallel queries: lists+embedded counts, and the caller's own
 * list_members rows for tracks_home. The original Logbook also fetched
 * "newCounts" for episode badges — deferred until items + episodes land
 * in Phases 4–5.
 */
interface RawMembershipJoinRow {
  pinned_at: string | null;
  sort_order: number;
  tracks_home: boolean;
  lists: RawListRow;
}

export function listsQueryOptions(user: User) {
  return {
    queryKey: listsQueryKey,
    queryFn: async (): Promise<{
      private: ListSummary[];
      shared: ListSummary[];
    }> => {
      // Two parallel queries: the lists+memberships join, and the items-
      // on-visible-lists pairs (with type for the folgen/kapitel split).
      // The pairs query subsumes both the "what items can the user see"
      // and the "what type is each" lookups that the previous helper did
      // in separate round-trips. RLS scopes the pairs to lists the user
      // is a member of.
      const [membershipRes, pairsRes] = await Promise.all([
        supabase
          .from("list_members")
          .select(
            `pinned_at, sort_order, tracks_home, lists!inner(${LIST_SELECT})`,
          )
          .eq("user_id", user.id),
        supabase
          .from("list_items")
          .select(
            "id, sync_enabled, display_weekday, list_id, item_id, items!inner(type)",
          )
          // Windowed by the user's total list_items (normally well under 1000).
          // NOTE: Supabase's hard 1000-row cap (db-max-rows) overrides this
          // `.limit` — a user with 1000+ list_items across all lists would
          // under-count badges past 1000 (no error, just a missing badge).
          // Acceptable at this app's scale; paginate with `.range()` if it ever
          // bites. (Same cap class as the co-watcher eye / title-gap fixes.)
          .limit(5000),
      ]);

      if (membershipRes.error) throw membershipRes.error;
      if (pairsRes.error)
        console.error("list_items pair lookup failed", pairsRes.error);

      // Flatten PostgREST's embedded { items: { type } } shape. Skip rows
      // where the items embed came back null (RLS edge-case — shouldn't
      // happen since lists+items share caller-visible scope, but defensive).
      const rawPairs = (pairsRes.data ?? []) as unknown as Array<{
        id: string;
        sync_enabled: boolean;
        display_weekday: number | null;
        list_id: string;
        item_id: string;
        items: { type: string } | null;
      }>;
      const flatPairs = rawPairs.flatMap((r) => {
        const type = r.items?.type;
        if (!type) return [];
        return [
          {
            list_id: r.list_id,
            listItemId: r.id,
            item_id: r.item_id,
            type,
            syncEnabled: r.sync_enabled,
            instanceWeekday: r.display_weekday,
          },
        ];
      });

      // Episode-window check runs serial-after the pairs because it needs the
      // candidate set. Per-list_item (sync-aware) so a synced instance and a
      // global entry of the same item get independent badges; see
      // findItemsWithNewEpisodes.
      const newEpisodeCounts = await findItemsWithNewEpisodes(
        user.id,
        flatPairs.map((p) => ({
          itemId: p.item_id,
          listItemId: p.listItemId,
          syncEnabled: p.syncEnabled,
          instanceWeekday: p.instanceWeekday,
        })),
      );
      const newCountsByList = aggregateNewCounts(flatPairs, newEpisodeCounts);

      const rows = (membershipRes.data ?? []) as unknown as RawMembershipJoinRow[];
      const summaries: ListSummary[] = rows
        .map((r) => ({
          ...toSummary(r.lists, user, {
            tracksHome: r.tracks_home,
            pinned: r.pinned_at !== null,
            sortOrder: r.sort_order,
          }),
          newCounts: newCountsByList.get(r.lists.id) ?? { ...EMPTY_COUNTS },
        }))
        .sort(bySectionThenSort);

      return {
        private: summaries.filter((l) => !l.isShared),
        shared: summaries.filter((l) => l.isShared),
      };
    },
  };
}

/** A single list by short_code, or null if not visible (RLS) / unknown
 *  code. Membership lookup happens after we've got the list-id, because
 *  list_members is keyed on the UUID. */
export function listQueryOptions(user: User, shortCode: string) {
  return {
    queryKey: listQueryKey(shortCode),
    queryFn: async (): Promise<ListSummary | null> => {
      const listRes = await supabase
        .from("lists")
        .select(LIST_SELECT)
        .eq("short_code", shortCode)
        .maybeSingle();

      if (listRes.error) throw listRes.error;
      if (!listRes.data) return null;

      const raw = listRes.data as unknown as RawListRow;
      const membershipRes = await supabase
        .from("list_members")
        .select("tracks_home, pinned_at, sort_order")
        .eq("list_id", raw.id)
        .eq("user_id", user.id)
        .maybeSingle();

      const m = membershipRes.data as
        | { tracks_home: boolean; pinned_at: string | null; sort_order: number }
        | null;
      return {
        ...toSummary(raw, user, {
          tracksHome: m?.tracks_home ?? true,
          pinned: m?.pinned_at != null,
          sortOrder: m?.sort_order ?? 0,
        }),
        // The single-list detail view doesn't render the per-list badge —
        // it shows per-item badges instead. Skip the new-counts roundtrip.
        newCounts: { ...EMPTY_COUNTS },
      };
    },
  };
}

interface RawListItemRow {
  id: string;
  sync_enabled: boolean;
  display_weekday: number | null;
  item_id: string;
  pinned_at: string | null;
  sort_order: number;
  items: {
    title: string;
    type: string;
    slug: string;
    cover_url: string | null;
  } | null;
}

/** Items placed in a list, ordered pinned-first then by sort_order ASC,
 *  scoped by the list's short_code. PostgREST `lists!inner(short_code)`
 *  does the FK join + filter in one round-trip; RLS still scopes the rows
 *  to lists the caller can see. Pin grouping happens client-side (see
 *  `bySectionThenSort` rationale on the lists query above).
 *
 *  Each entry gets a per-user `hasNewEpisode` flag derived from the same
 *  findItemsWithNewEpisodes() helper that powers the overview badge,
 *  called here scoped to this list's items only. */
export function listItemsQueryOptions(user: User, shortCode: string) {
  return {
    queryKey: listItemsQueryKey(shortCode),
    queryFn: async (): Promise<ListEntry[]> => {
      // Scoped fetch: this list's list_items + the embedded items meta
      // (title/type/slug/cover_url). The itemIds extracted from the
      // response bound the new-episode check below — no need to scan the
      // user's entire catalogue the way the previous global helper did.
      const { data, error } = await supabase
        .from("list_items")
        .select(
          "id, sync_enabled, display_weekday, item_id, pinned_at, sort_order, lists!inner(short_code), items(title, type, slug, cover_url)",
        )
        .eq("lists.short_code", shortCode);
      if (error) throw error;

      const rawRows = (data as unknown as RawListItemRow[]) ?? [];
      const newEpisodeCounts = await findItemsWithNewEpisodes(
        user.id,
        rawRows.map((r) => ({
          itemId: r.item_id,
          listItemId: r.id,
          syncEnabled: r.sync_enabled,
          instanceWeekday: r.display_weekday,
        })),
      );

      const rows = rawRows.map((r) => {
        const count = newEpisodeCounts.get(r.id) ?? 0;
        return {
          listItemId: r.id,
          itemId: r.item_id,
          type: r.items?.type ?? "anime",
          slug: r.items?.slug ?? "",
          title: r.items?.title ?? "Unbekannt",
          coverUrl: r.items?.cover_url ?? null,
          syncEnabled: r.sync_enabled,
          pinned: r.pinned_at !== null,
          sortOrder: r.sort_order,
          hasNewEpisode: count > 0,
          newEpisodeCount: count,
        };
      });
      return rows.sort((a, b) => {
        if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
        return a.sortOrder - b.sortOrder;
      });
    },
  };
}

// ──────────────────────────────────────────────────────────────────────────
// Mutations — components compose these via createMutation
// ──────────────────────────────────────────────────────────────────────────

export async function createList(
  user: User,
  input: { name: string; description?: string; category?: ListCategory | null },
): Promise<ListSummary> {
  const name = input.name.trim();
  if (!name) throw new Error("Name darf nicht leer sein.");

  const { data, error } = await supabase
    .from("lists")
    .insert({
      owner_id: user.id,
      name,
      description: input.description?.trim() || null,
      category: input.category ?? null,
    })
    .select(LIST_SELECT)
    .single();

  if (error) throw error;
  // The on_list_created trigger added the owner to list_members with
  // tracks_home=true automatically. The new list_members row gets
  // pinned_at=null and a sort_order assigned by the BEFORE-INSERT trigger
  // (MIN(scope)-1 → top of unpinned section). We don't read those back
  // here — the next invalidation refresh picks them up. For the optimistic
  // returnee we use safe defaults.
  return {
    ...toSummary(data as unknown as RawListRow, user, {
      tracksHome: true,
      pinned: false,
      sortOrder: 0,
    }),
    // A fresh list has no items yet — definitely no new episodes.
    newCounts: { ...EMPTY_COUNTS },
  };
}

/**
 * Rename. RLS (lists_update_member) lets any member rename. We `.select()`
 * the persisted name back so an RLS-blocked write (0 rows, no error)
 * surfaces as a returned `name: null` — components compare to detect the
 * silent block.
 */
export async function renameList(input: {
  listId: string;
  name: string;
}): Promise<{ name: string | null }> {
  const next = input.name.trim();
  if (!next) return { name: null };

  const { data, error } = await supabase
    .from("lists")
    .update({ name: next })
    .eq("id", input.listId)
    .select("name")
    .maybeSingle();
  if (error) throw error;
  return { name: (data as { name: string } | null)?.name ?? null };
}

/** Set (or clear) a list's description. Owner-only via RLS (lists_update_owner);
 *  mirrors renameList. Unlike the name, an empty value is legal — it clears the
 *  description (stored as null). `.select()` + the 0-row check distinguishes a
 *  legit null result (cleared) from an RLS-silently-blocked write. */
export async function updateListDescription(input: {
  listId: string;
  description: string | null;
}): Promise<{ description: string | null; blocked: boolean }> {
  const next = input.description?.trim() || null;
  const { data, error } = await supabase
    .from("lists")
    .update({ description: next })
    .eq("id", input.listId)
    .select("description")
    .maybeSingle();
  if (error) throw error;
  if (!data) return { description: null, blocked: true };
  return {
    description: (data as { description: string | null }).description,
    blocked: false,
  };
}

/** Set (or clear) a list's media category. Owner-only via RLS
 *  (lists_update_owner); mirrors updateListDescription. null = "Alle"
 *  (uncategorized). `.select()` + the 0-row check distinguishes a legit
 *  result from an RLS-silently-blocked write (a non-owner). Existing
 *  mismatched items are NOT touched — the UI warns about them (dulden+warnen),
 *  enforcement only applies to NEW adds via the AddSheet. */
export async function updateListCategory(input: {
  listId: string;
  category: ListCategory | null;
}): Promise<{ category: ListCategory | null; blocked: boolean }> {
  const { data, error } = await supabase
    .from("lists")
    .update({ category: input.category })
    .eq("id", input.listId)
    .select("category")
    .maybeSingle();
  if (error) throw error;
  if (!data) return { category: null, blocked: true };
  return {
    category: (data as { category: ListCategory | null }).category,
    blocked: false,
  };
}

/** Delete a list. RLS (lists_delete_owner) restricts to the creator; the
 *  cascade on list_items / list_members / list_invitations cleans the rest.
 *
 *  `.select()` + null-check defends against a UI race where the caller
 *  loses ownership between render-time and click — e.g. an in-flight
 *  ownership transfer (Phase 7+). Without the check the optimistic UI
 *  would happily remove a list that's still on the server. */
export async function deleteList(listId: string): Promise<void> {
  const { data, error } = await supabase
    .from("lists")
    .delete()
    .eq("id", listId)
    .select("id")
    .maybeSingle();
  if (error) throw error;
  if (data === null)
    throw new Error("Liste konnte nicht gelöscht werden.");
}

/** Remove an item from a list (delete the list_items row). The item itself
 *  stays in `items` — it's still in the catalogue, just no longer on this
 *  list. Watch progress is keyed on items.id, so it's preserved even if the
 *  same item gets re-added later.
 *
 *  `.select()` after the delete so a silent RLS block (0 rows, no error)
 *  surfaces as a thrown error instead of the optimistic UI claiming success
 *  while the row stays in the table. */
export async function removeListItem(listItemId: string): Promise<void> {
  const { data, error } = await supabase
    .from("list_items")
    .delete()
    .eq("id", listItemId)
    .select("id")
    .maybeSingle();
  if (error) throw error;
  if (data === null)
    throw new Error("Eintrag konnte nicht entfernt werden.");
}

/** Move a list_items row to a different list. Sync is reset to false because
 *  the new list may have different members — if the caller wants sync in the
 *  new list, they re-enable it there (handshake §Phase 7).
 *
 *  CRITICAL: if the item is currently synced, we must run the REAL un-sync
 *  (`unsync_item`) BEFORE the move — not just flip `sync_enabled=false`. A bare
 *  flip strands data: the mover's progress lives in the instance lane
 *  (`list_item_id = LI`), so after the move the global-lane reads show the item
 *  as unwatched; and co-members' instance watch rows would orphan onto a
 *  list_item that now lives in a (possibly private) different list — a stale,
 *  privacy-leaky residue that re-surfaced as the "ghost co-watcher eye" bug.
 *  `unsync_item` unions every member's instance progress back into their own
 *  global lane (never loses progress), tears the instance down, and sets
 *  sync_enabled=false. We call it while the row is STILL in the source (shared)
 *  list so the member-scoped merge is correct.
 *
 *  `.select()` + null-check same rationale as removeListItem above. */
export async function moveListItem(input: {
  listItemId: string;
  targetListId: string;
}): Promise<void> {
  const { data: li, error: liErr } = await supabase
    .from("list_items")
    .select("sync_enabled")
    .eq("id", input.listItemId)
    .maybeSingle();
  if (liErr) throw liErr;
  if (li === null)
    throw new Error("Eintrag konnte nicht verschoben werden.");

  if (li.sync_enabled) {
    const { error: unsyncErr } = await supabase.rpc("unsync_item", {
      _list_item_id: input.listItemId,
    });
    if (unsyncErr) throw unsyncErr;
  }

  const { data, error } = await supabase
    .from("list_items")
    .update({ list_id: input.targetListId, sync_enabled: false })
    .eq("id", input.listItemId)
    .select("id")
    .maybeSingle();
  if (error) throw error;
  if (data === null)
    throw new Error("Eintrag konnte nicht verschoben werden.");
}

/**
 * Toggle the per-user tracks_home flag. Archive (off) = items in this list
 * drop off Home / Calendar / Logbook for the caller only; other members keep
 * their own setting.
 *
 * Routes through the `set_list_tracking` DEFINER RPC, NOT a direct UPDATE: the
 * list_members UPDATE policy is owner-only, so a member's direct write was
 * silently RLS-blocked and the toggle bounced back. The RPC self-scopes to the
 * caller's own membership (mirrors set_list_pin). Returns the new tracks_home,
 * or null when the caller isn't a member of the list (so a no-op still reverts).
 */
export async function setListTracking(
  user: User,
  input: { listId: string; enabled: boolean },
): Promise<{ tracksHome: boolean | null }> {
  const { data, error } = await supabase.rpc("set_list_tracking", {
    _user_id: user.id,
    _list_id: input.listId,
    _enabled: input.enabled,
  });
  if (error) throw error;
  return { tracksHome: (data as boolean | null) ?? null };
}

/**
 * Toggle the per-user list pin via the `set_list_pin` RPC. The RPC assigns
 * sort_order server-side (`MIN(target section) - 1`) in the SAME statement
 * that flips pinned_at, so there's no client-read-then-write gap to race
 * against a concurrent `reorder_list_members` (B1 — the pin used to send a
 * sort_order computed from a possibly-stale cache). Throws on access-denied /
 * RLS block, surfacing as a mutation error rather than a silent no-op.
 *
 * The caller still computes the target sort_order for its OPTIMISTIC cache
 * patch (so the row jumps to the top instantly); the server value is
 * authoritative and the onSettled invalidation reconciles the two.
 */
export async function setListPin(input: {
  listId: string;
  userId: string;
  pinned: boolean;
}): Promise<void> {
  const { error } = await supabase.rpc("set_list_pin", {
    _user_id: input.userId,
    _list_id: input.listId,
    _pinned: input.pinned,
  });
  if (error) throw error;
}

/**
 * Toggle the shared per-list item pin via the `set_list_item_pin` RPC. Same
 * server-side sort_order assignment + single-statement atomicity rationale as
 * setListPin (B1).
 */
export async function setListItemPin(input: {
  listItemId: string;
  pinned: boolean;
}): Promise<void> {
  const { error } = await supabase.rpc("set_list_item_pin", {
    _list_item_id: input.listItemId,
    _pinned: input.pinned,
  });
  if (error) throw error;
}

/**
 * Atomic reorder of the caller's list_members rows for one pin section.
 * Goes through the `reorder_list_members` RPC: a single UPDATE statement
 * server-side, so every realtime subscriber sees a consistent post-write
 * state. The previous parallel-UPDATE implementation fired N events at
 * different times, and a refetch landing between them would read a
 * partial state — that's the "hover bg flickers 2-3 times after drop"
 * the user was hitting.
 */
export async function reorderLists(input: {
  userId: string;
  orderedListIds: string[];
}): Promise<void> {
  const { error } = await supabase.rpc("reorder_list_members", {
    _user_id: input.userId,
    _ordered_list_ids: input.orderedListIds,
  });
  if (error) throw error;
}

/** Atomic reorder of one pin section of a list's list_items, via the
 *  `reorder_list_items` RPC. Same single-UPDATE rationale as reorderLists.
 *  `listId` is required so the server-side authorization check (caller
 *  must be a member of the list) has a target. */
export async function reorderListItems(input: {
  listId: string;
  orderedListItemIds: string[];
}): Promise<void> {
  const { error } = await supabase.rpc("reorder_list_items", {
    _list_id: input.listId,
    _ordered_list_item_ids: input.orderedListItemIds,
  });
  if (error) throw error;
}

// ──────────────────────────────────────────────────────────────────────────
// List covers — owner-uploaded custom image (overrides the generated cover).
// Bucket + storage RLS from migration 20260601150000; only the list owner may
// write (the bucket policy checks lists.owner_id against the <list_id> folder,
// and the cover_url write rides the owner-only lists_update_owner policy).
// ──────────────────────────────────────────────────────────────────────────

export const MAX_COVER_BYTES = 10 * 1024 * 1024; // 10 MB (cropper recompresses)

/** Upload a cropped cover image to the `list-covers` bucket, return its public
 *  URL. Stable path `<list_id>/cover.<ext>` + upsert → re-upload overwrites in
 *  place. `?v=<ts>` cache-busts so members fetch the new image. */
export async function uploadListCover(input: {
  listId: string;
  file: File;
}): Promise<string> {
  const ext = (input.file.name.split(".").pop() || "jpg")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
  const path = `${input.listId}/cover.${ext || "jpg"}`;

  const { error: uploadError } = await supabase.storage
    .from("list-covers")
    .upload(path, input.file, {
      upsert: true,
      contentType: input.file.type || "image/jpeg",
      cacheControl: "3600",
    });
  if (uploadError) throw uploadError;

  const { data } = supabase.storage.from("list-covers").getPublicUrl(path);
  return `${data.publicUrl}?v=${Date.now()}`;
}

/** Write lists.cover_url (owner only — guarded by lists_update_owner). Pass
 *  null to clear the custom cover and fall back to the generated one.
 *  `.select()` back to detect a silent RLS block (0 rows, no error). */
export async function setListCover(input: {
  listId: string;
  coverUrl: string | null;
}): Promise<{ coverUrl: string | null; blocked: boolean }> {
  const { data, error } = await supabase
    .from("lists")
    .update({ cover_url: input.coverUrl })
    .eq("id", input.listId)
    .select("cover_url")
    .maybeSingle();
  if (error) throw error;
  if (!data) return { coverUrl: null, blocked: true };
  return { coverUrl: (data as { cover_url: string | null }).cover_url, blocked: false };
}
