import { supabase } from "@/lib/supabase";
import type { User } from "@supabase/supabase-js";
import { embedCount, unique } from "@/lib/format";

/**
 * Lists data layer — typed query options + mutation functions. Components
 * call these via createQuery / createMutation from @tanstack/solid-query.
 *
 * Naming convention:
 *   - listsQueryKey()             — overview (all visible lists)
 *   - listQueryKey(id)            — single list detail
 *   - listItemsQueryKey(id)       — items inside one list
 *
 * Mutations invalidate the keys they touch. Realtime subscriptions (added in
 * the chunk after this) call queryClient.invalidateQueries on the same keys
 * so a partner's write flows to your screen the same way your own does —
 * one source of truth for "this data changed", whether the trigger was local
 * or remote.
 *
 * RLS does the visibility filtering on every query — we never pass user_id
 * filters explicitly; lists_select_member + list_items_select_member +
 * list_members_select_co already scope the rows correctly.
 */

// ──────────────────────────────────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────────────────────────────────

export interface ListSummary {
  /** UUID — used for RPC calls (delete, rename, set-tracks-home). */
  id: string;
  /** URL-stable identifier — `adj-adj-noun`, generated by the DB trigger
   *  `lists_set_short_code_trigger` on insert. Used in `/lists/<shortCode>`
   *  and in TanStack-Query keys. */
  shortCode: string;
  name: string;
  description: string | null;
  isShared: boolean;
  /** Caller's per-user tracks_home flag. Off → archive (lists I created but
   *  don't want to surface on Home / Calendar). */
  tracksHome: boolean;
  ownerId: string;
  createdAt: string;
  itemCount: number;
  memberCount: number;
  /** True when the caller is the list's creator. Used to gate the "Liste
   *  löschen" action (everyone else gets "Liste verlassen" once sharing
   *  lands). */
  isOwner: boolean;
  /** Caller's per-user pin state. Pinned lists float to the top of the
   *  caller's /lists view (independent of what other members see). */
  pinned: boolean;
  /** Caller's per-user manual sort_order. Higher pin / lower sort_order =
   *  closer to the top within its pin section. */
  sortOrder: number;
  /** Counts of items with released-but-unwatched episodes/chapters in the
   *  last NEW_WINDOW_DAYS — drives the "Neue Folge" / "N neue Folgen" badge
   *  on /lists rows. Manga have no air-date signal, so the kapitel side
   *  stays 0 until that source lands (Welle-2). */
  newCounts: { folgen: number; kapitel: number };
}

export interface ListEntry {
  listItemId: string;
  itemId: string;
  /** (type, slug) is the natural key used in `/item/:type/:slug`. */
  type: string;
  slug: string;
  title: string;
  coverUrl: string | null;
  syncEnabled: boolean;
  /** Shared per-list pin state. Pinning an item is visible to every member
   *  of the list, unlike the per-user list pin above. */
  pinned: boolean;
  sortOrder: number;
  /** True when at least one episode of this item aired within the last
   *  NEW_WINDOW_DAYS and the caller hasn't ticked it yet. Drives the
   *  "Neue Folge" badge in the list-detail row. Per-user — co-members
   *  evaluate the same item independently against their own watches. */
  hasNewEpisode: boolean;
}

// ──────────────────────────────────────────────────────────────────────────
// Query keys — exported so realtime + mutations can invalidate by key
// ──────────────────────────────────────────────────────────────────────────

export const listsQueryKey = ["lists"] as const;
// Per-list keys are now indexed by shortCode (URL-stable). Realtime
// invalidations use this key + a channel name derived from the shortCode.
export const listQueryKey = (shortCode: string) =>
  ["list", shortCode] as const;
export const listItemsQueryKey = (shortCode: string) =>
  ["list", shortCode, "items"] as const;

// ──────────────────────────────────────────────────────────────────────────
// Query options — pass to createQuery() in components
// ──────────────────────────────────────────────────────────────────────────

/** PostgREST embed shape — list_items(count) and list_members(count) return
 *  as a single-element array of { count }. */
interface RawListRow {
  id: string;
  short_code: string;
  name: string;
  description: string | null;
  is_shared: boolean;
  owner_id: string;
  created_at: string;
  list_items: { count: number }[] | null;
  list_members: { count: number }[] | null;
}

const LIST_SELECT =
  "id, short_code, name, description, is_shared, owner_id, created_at, list_items(count), list_members(count)";

function toSummary(
  row: RawListRow,
  user: User,
  membership: { tracksHome: boolean; pinned: boolean; sortOrder: number },
): Omit<ListSummary, "newCounts"> {
  return {
    id: row.id,
    shortCode: row.short_code,
    name: row.name,
    description: row.description,
    isShared: row.is_shared,
    tracksHome: membership.tracksHome,
    ownerId: row.owner_id,
    createdAt: row.created_at,
    itemCount: embedCount(row.list_items),
    memberCount: embedCount(row.list_members),
    isOwner: row.owner_id === user.id,
    pinned: membership.pinned,
    sortOrder: membership.sortOrder,
  };
}

/** Empty new-counts default — used in places where we don't have the
 *  newItemsMap (single-list query, optimistic createList return). */
const EMPTY_COUNTS = { folgen: 0, kapitel: 0 } as const;

/** Pinned-first, then by sort_order ASC within each section. Server can't
 *  express "group by (pinned_at IS NULL) then sort by sort_order" without a
 *  generated column or RPC, so we group client-side. With < 100 lists this
 *  is free. */
function bySectionThenSort(a: ListSummary, b: ListSummary): number {
  if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
  return a.sortOrder - b.sortOrder;
}

/** Window matching the Logbuch's "missed" definition — a released episode
 *  counts as "new" if it aired in the last NEW_WINDOW_DAYS and the user
 *  hasn't ticked it. Keeps the lists badge and the home modules in sync. */
const NEW_WINDOW_DAYS = 14;

/**
 * Filters `itemIds` down to the subset that have at least one released-
 * but-unwatched episode inside the new-window. Two round-trips: episodes
 * in window, then the caller's watches over them.
 *
 * The candidate item set is passed in so the caller can scope it — e.g.
 * `listItemsQueryOptions` only cares about items in ONE list and no longer
 * needs to scan the user's full catalogue. Item-type resolution lives
 * with the caller (who already has it from their main fetch), saving the
 * previous fourth round-trip to `items`.
 */
async function findItemsWithNewEpisodes(
  userId: string,
  itemIds: string[],
): Promise<Set<string>> {
  if (itemIds.length === 0) return new Set();

  const sinceIso = new Date(
    Date.now() - NEW_WINDOW_DAYS * 86_400_000,
  ).toISOString();
  const nowIso = new Date().toISOString();
  const { data: epRows, error: epErr } = await supabase
    .from("episodes")
    .select("id, item_id")
    .in("item_id", itemIds)
    .gte("air_date", sinceIso)
    .lte("air_date", nowIso);
  if (epErr) {
    console.error("episodes window query failed", epErr);
    return new Set();
  }
  const eps = (epRows ?? []) as { id: string; item_id: string }[];
  if (eps.length === 0) return new Set();

  const { data: wRows, error: wErr } = await supabase
    .from("episode_watches")
    .select("episode_id")
    .in(
      "episode_id",
      eps.map((e) => e.id),
    )
    .eq("user_id", userId);
  if (wErr) {
    console.error("episode_watches join failed", wErr);
    return new Set();
  }
  const watched = new Set((wRows ?? []).map((w) => w.episode_id as string));

  const result = new Set<string>();
  for (const e of eps) if (!watched.has(e.id)) result.add(e.item_id);
  return result;
}

/** Aggregate (list_id, item_id, type) pairs into per-list (folgen, kapitel)
 *  counts, filtered to the items that qualified as new. anime/series count
 *  as Folgen, manga as Kapitel; movies/games are ignored (no episode model).
 *  Type travels alongside the pair so we don't need a separate items lookup. */
function aggregateNewCounts(
  pairs: { list_id: string; item_id: string; type: string }[],
  newItemsSet: Set<string>,
): Map<string, { folgen: number; kapitel: number }> {
  const counts = new Map<string, { folgen: number; kapitel: number }>();
  for (const p of pairs) {
    if (!newItemsSet.has(p.item_id)) continue;
    const c = counts.get(p.list_id) ?? { folgen: 0, kapitel: 0 };
    if (p.type === "manga") c.kapitel++;
    else if (p.type === "anime" || p.type === "series") c.folgen++;
    counts.set(p.list_id, c);
  }
  return counts;
}

/**
 * All lists visible to the current user (RLS scopes via lists_select_member).
 * Split into private / shared so the UI can render the two groups; the split
 * is by is_shared, not ownership — a list you created becomes "geteilt" the
 * moment you invite someone (Phase 7+).
 *
 * Two parallel queries: lists+embedded counts, and the caller's own
 * list_members rows for tracks_home. The original Logbook also fetched
 * "newCounts" for episode badges — deferred until items + episodes land
 * in Phases 4–5.
 */
interface RawMembershipJoinRow {
  pinned_at: string | null;
  sort_order: number;
  tracks_home: boolean;
  lists: RawListRow;
}

export function listsQueryOptions(user: User) {
  return {
    queryKey: listsQueryKey,
    queryFn: async (): Promise<{
      private: ListSummary[];
      shared: ListSummary[];
    }> => {
      // Two parallel queries: the lists+memberships join, and the items-
      // on-visible-lists pairs (with type for the folgen/kapitel split).
      // The pairs query subsumes both the "what items can the user see"
      // and the "what type is each" lookups that the previous helper did
      // in separate round-trips. RLS scopes the pairs to lists the user
      // is a member of.
      const [membershipRes, pairsRes] = await Promise.all([
        supabase
          .from("list_members")
          .select(
            `pinned_at, sort_order, tracks_home, lists!inner(${LIST_SELECT})`,
          )
          .eq("user_id", user.id),
        supabase
          .from("list_items")
          .select("list_id, item_id, items!inner(type)"),
      ]);

      if (membershipRes.error) throw membershipRes.error;
      if (pairsRes.error)
        console.error("list_items pair lookup failed", pairsRes.error);

      // Flatten PostgREST's embedded { items: { type } } shape. Skip rows
      // where the items embed came back null (RLS edge-case — shouldn't
      // happen since lists+items share caller-visible scope, but defensive).
      const rawPairs = (pairsRes.data ?? []) as unknown as Array<{
        list_id: string;
        item_id: string;
        items: { type: string } | null;
      }>;
      const flatPairs = rawPairs.flatMap((r) => {
        const type = r.items?.type;
        if (!type) return [];
        return [{ list_id: r.list_id, item_id: r.item_id, type }];
      });
      const itemIds = unique(flatPairs.map((p) => p.item_id));

      // Episode-window check runs serial-after the pairs because it needs
      // the candidate item set. Two more round-trips inside; see
      // findItemsWithNewEpisodes.
      const newItemsSet = await findItemsWithNewEpisodes(user.id, itemIds);
      const newCountsByList = aggregateNewCounts(flatPairs, newItemsSet);

      const rows = (membershipRes.data ?? []) as unknown as RawMembershipJoinRow[];
      const summaries: ListSummary[] = rows
        .map((r) => ({
          ...toSummary(r.lists, user, {
            tracksHome: r.tracks_home,
            pinned: r.pinned_at !== null,
            sortOrder: r.sort_order,
          }),
          newCounts: newCountsByList.get(r.lists.id) ?? { ...EMPTY_COUNTS },
        }))
        .sort(bySectionThenSort);

      return {
        private: summaries.filter((l) => !l.isShared),
        shared: summaries.filter((l) => l.isShared),
      };
    },
  };
}

/** A single list by short_code, or null if not visible (RLS) / unknown
 *  code. Membership lookup happens after we've got the list-id, because
 *  list_members is keyed on the UUID. */
export function listQueryOptions(user: User, shortCode: string) {
  return {
    queryKey: listQueryKey(shortCode),
    queryFn: async (): Promise<ListSummary | null> => {
      const listRes = await supabase
        .from("lists")
        .select(LIST_SELECT)
        .eq("short_code", shortCode)
        .maybeSingle();

      if (listRes.error) throw listRes.error;
      if (!listRes.data) return null;

      const raw = listRes.data as unknown as RawListRow;
      const membershipRes = await supabase
        .from("list_members")
        .select("tracks_home, pinned_at, sort_order")
        .eq("list_id", raw.id)
        .eq("user_id", user.id)
        .maybeSingle();

      const m = membershipRes.data as
        | { tracks_home: boolean; pinned_at: string | null; sort_order: number }
        | null;
      return {
        ...toSummary(raw, user, {
          tracksHome: m?.tracks_home ?? true,
          pinned: m?.pinned_at != null,
          sortOrder: m?.sort_order ?? 0,
        }),
        // The single-list detail view doesn't render the per-list badge —
        // it shows per-item badges instead. Skip the new-counts roundtrip.
        newCounts: { ...EMPTY_COUNTS },
      };
    },
  };
}

interface RawListItemRow {
  id: string;
  sync_enabled: boolean;
  item_id: string;
  pinned_at: string | null;
  sort_order: number;
  items: {
    title: string;
    type: string;
    slug: string;
    cover_url: string | null;
  } | null;
}

/** Items placed in a list, ordered pinned-first then by sort_order ASC,
 *  scoped by the list's short_code. PostgREST `lists!inner(short_code)`
 *  does the FK join + filter in one round-trip; RLS still scopes the rows
 *  to lists the caller can see. Pin grouping happens client-side (see
 *  `bySectionThenSort` rationale on the lists query above).
 *
 *  Each entry gets a per-user `hasNewEpisode` flag derived from the same
 *  findItemsWithNewEpisodes() helper that powers the overview badge,
 *  called here scoped to this list's items only. */
export function listItemsQueryOptions(user: User, shortCode: string) {
  return {
    queryKey: listItemsQueryKey(shortCode),
    queryFn: async (): Promise<ListEntry[]> => {
      // Scoped fetch: this list's list_items + the embedded items meta
      // (title/type/slug/cover_url). The itemIds extracted from the
      // response bound the new-episode check below — no need to scan the
      // user's entire catalogue the way the previous global helper did.
      const { data, error } = await supabase
        .from("list_items")
        .select(
          "id, sync_enabled, item_id, pinned_at, sort_order, lists!inner(short_code), items(title, type, slug, cover_url)",
        )
        .eq("lists.short_code", shortCode);
      if (error) throw error;

      const rawRows = (data as unknown as RawListItemRow[]) ?? [];
      const itemIds = unique(rawRows.map((r) => r.item_id));
      const newItemsSet = await findItemsWithNewEpisodes(user.id, itemIds);

      const rows = rawRows.map((r) => ({
        listItemId: r.id,
        itemId: r.item_id,
        type: r.items?.type ?? "anime",
        slug: r.items?.slug ?? "",
        title: r.items?.title ?? "Unbekannt",
        coverUrl: r.items?.cover_url ?? null,
        syncEnabled: r.sync_enabled,
        pinned: r.pinned_at !== null,
        sortOrder: r.sort_order,
        hasNewEpisode: newItemsSet.has(r.item_id),
      }));
      return rows.sort((a, b) => {
        if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
        return a.sortOrder - b.sortOrder;
      });
    },
  };
}

// ──────────────────────────────────────────────────────────────────────────
// Mutations — components compose these via createMutation
// ──────────────────────────────────────────────────────────────────────────

export async function createList(
  user: User,
  input: { name: string; description?: string },
): Promise<ListSummary> {
  const name = input.name.trim();
  if (!name) throw new Error("Name darf nicht leer sein.");

  const { data, error } = await supabase
    .from("lists")
    .insert({
      owner_id: user.id,
      name,
      description: input.description?.trim() || null,
    })
    .select(LIST_SELECT)
    .single();

  if (error) throw error;
  // The on_list_created trigger added the owner to list_members with
  // tracks_home=true automatically. The new list_members row gets
  // pinned_at=null and a sort_order assigned by the BEFORE-INSERT trigger
  // (MIN(scope)-1 → top of unpinned section). We don't read those back
  // here — the next invalidation refresh picks them up. For the optimistic
  // returnee we use safe defaults.
  return {
    ...toSummary(data as unknown as RawListRow, user, {
      tracksHome: true,
      pinned: false,
      sortOrder: 0,
    }),
    // A fresh list has no items yet — definitely no new episodes.
    newCounts: { ...EMPTY_COUNTS },
  };
}

/**
 * Rename. RLS (lists_update_member) lets any member rename. We `.select()`
 * the persisted name back so an RLS-blocked write (0 rows, no error)
 * surfaces as a returned `name: null` — components compare to detect the
 * silent block.
 */
export async function renameList(input: {
  listId: string;
  name: string;
}): Promise<{ name: string | null }> {
  const next = input.name.trim();
  if (!next) return { name: null };

  const { data, error } = await supabase
    .from("lists")
    .update({ name: next })
    .eq("id", input.listId)
    .select("name")
    .maybeSingle();
  if (error) throw error;
  return { name: (data as { name: string } | null)?.name ?? null };
}

/** Delete a list. RLS (lists_delete_owner) restricts to the creator; the
 *  cascade on list_items / list_members / list_invitations cleans the rest. */
export async function deleteList(listId: string): Promise<void> {
  const { error } = await supabase.from("lists").delete().eq("id", listId);
  if (error) throw error;
}

/** Remove an item from a list (delete the list_items row). The item itself
 *  stays in `items` — it's still in the catalogue, just no longer on this
 *  list. Watch progress is keyed on items.id, so it's preserved even if the
 *  same item gets re-added later.
 *
 *  `.select()` after the delete so a silent RLS block (0 rows, no error)
 *  surfaces as a thrown error instead of the optimistic UI claiming success
 *  while the row stays in the table. */
export async function removeListItem(listItemId: string): Promise<void> {
  const { data, error } = await supabase
    .from("list_items")
    .delete()
    .eq("id", listItemId)
    .select("id")
    .maybeSingle();
  if (error) throw error;
  if (data === null)
    throw new Error("Eintrag konnte nicht entfernt werden.");
}

/** Move a list_items row to a different list. Sync is reset to false because
 *  the new list may have different members — if the caller wants sync in the
 *  new list, they re-enable it there (handshake §Phase 7).
 *
 *  `.select()` + null-check same rationale as removeListItem above. */
export async function moveListItem(input: {
  listItemId: string;
  targetListId: string;
}): Promise<void> {
  const { data, error } = await supabase
    .from("list_items")
    .update({ list_id: input.targetListId, sync_enabled: false })
    .eq("id", input.listItemId)
    .select("id")
    .maybeSingle();
  if (error) throw error;
  if (data === null)
    throw new Error("Eintrag konnte nicht verschoben werden.");
}

/**
 * Toggle the per-user tracks_home flag. Off = archive mode for the caller
 * only — items in this list drop off Home / Calendar / Logbook for them.
 * Other members keep their own setting.
 *
 * `.select()` to detect silent RLS blocks (0 rows updated, no error).
 */
export async function setListTracking(
  user: User,
  input: { listId: string; enabled: boolean },
): Promise<{ tracksHome: boolean | null }> {
  const { data, error } = await supabase
    .from("list_members")
    .update({ tracks_home: input.enabled })
    .eq("list_id", input.listId)
    .eq("user_id", user.id)
    .select("tracks_home")
    .maybeSingle();
  if (error) throw error;
  return {
    tracksHome:
      (data as { tracks_home: boolean } | null)?.tracks_home ?? null,
  };
}

/**
 * Toggle the per-user list pin on `list_members`. Also assigns a fresh
 * sort_order so the pinned (or freshly-unpinned) list lands at the TOP of
 * its new section — `MIN(section.sort_order) - 1`. The caller computes
 * `sortOrder` from the current query cache so we don't need an extra
 * round-trip. Returns the post-write pinned state so the caller can
 * detect silent RLS blocks (0 rows → null).
 */
export async function setListPin(input: {
  listId: string;
  userId: string;
  pinned: boolean;
  sortOrder: number;
}): Promise<{ pinned: boolean | null }> {
  const { data, error } = await supabase
    .from("list_members")
    .update({
      pinned_at: input.pinned ? new Date().toISOString() : null,
      sort_order: input.sortOrder,
    })
    .eq("list_id", input.listId)
    .eq("user_id", input.userId)
    .select("pinned_at")
    .maybeSingle();
  if (error) throw error;
  return {
    pinned: data ? (data as { pinned_at: string | null }).pinned_at !== null : null,
  };
}

/**
 * Toggle the shared per-list pin on `list_items`. Same sortOrder-bump
 * pattern as setListPin so the pinned/unpinned item floats to the top of
 * its new section.
 */
export async function setListItemPin(input: {
  listItemId: string;
  pinned: boolean;
  sortOrder: number;
}): Promise<{ pinned: boolean | null }> {
  const { data, error } = await supabase
    .from("list_items")
    .update({
      pinned_at: input.pinned ? new Date().toISOString() : null,
      sort_order: input.sortOrder,
    })
    .eq("id", input.listItemId)
    .select("pinned_at")
    .maybeSingle();
  if (error) throw error;
  return {
    pinned: data ? (data as { pinned_at: string | null }).pinned_at !== null : null,
  };
}

/**
 * Atomic reorder of the caller's list_members rows for one pin section.
 * Goes through the `reorder_list_members` RPC: a single UPDATE statement
 * server-side, so every realtime subscriber sees a consistent post-write
 * state. The previous parallel-UPDATE implementation fired N events at
 * different times, and a refetch landing between them would read a
 * partial state — that's the "hover bg flickers 2-3 times after drop"
 * the user was hitting.
 */
export async function reorderLists(input: {
  userId: string;
  orderedListIds: string[];
}): Promise<void> {
  const { error } = await supabase.rpc("reorder_list_members", {
    _user_id: input.userId,
    _ordered_list_ids: input.orderedListIds,
  });
  if (error) throw error;
}

/** Atomic reorder of one pin section of a list's list_items, via the
 *  `reorder_list_items` RPC. Same single-UPDATE rationale as reorderLists.
 *  `listId` is required so the server-side authorization check (caller
 *  must be a member of the list) has a target. */
export async function reorderListItems(input: {
  listId: string;
  orderedListItemIds: string[];
}): Promise<void> {
  const { error } = await supabase.rpc("reorder_list_items", {
    _list_id: input.listId,
    _ordered_list_item_ids: input.orderedListItemIds,
  });
  if (error) throw error;
}
